### ISSUE TITLE
Amulet of Wisdom appears to be missing

### ISSUE THREAD

**Issue by marcjohnston** [Gurbintroll/Cthangband#11]
It appears this item might have been lost.  Was this by design?

**Comment by Gurbintroll** [comment]
It's not a lost item, it's an incorrect variable name - Amulet subcategory 6 is for amulets of brilliance, but they are incorrectly called amulets of wisdom in the code.

I've gone through and fixed all the incorrect subcategory variable names to match the actual names (other than this one, the rest were nearly all artifact names that I'd changed in the artifact file and enumeration but not in the subcategory variables.
