### ISSUE TITLE
ScrollEnchantWeapon and ScrollSpecialEnchantWeapon are duplicate in the .csv

### ISSUE THREAD

**Issue by marcjohnston** [Gurbintroll/Cthangband#15]
the .csv for item types has a duplicate scroll ScrollEnchantWeapon and ScrollSpecialEnchantWeapon are duplicate with duplicate subcategories.  I’m deleting the non-special version in my fork.

**Comment by Gurbintroll** [comment]
I'm not sure what you mean - BaseItemTypes.csv has "Scroll:Enchant Weapon To-Hit", "Scroll:Enchant Weapon To-Dam", and "Scroll:*Enchant Weapon*". It has neither ScrollEnchantWeapon nor ScrollSpecialEnchantWeapon.

**Comment by marcjohnston** [comment]
Not sure ... I thought I confirmed duplicate subcategory 21 on the scrolls.
