### ISSUE TITLE
DisplayPlayerAbilityScoresWithModifiers logic always true

### ISSUE THREAD

**Issue by marcjohnston** [Gurbintroll/Cthangband#16]
the CharacterViewer.DisplayPlayerAbilityScoresWithModifiers method has an embedded IF statement that is always true ...
it is more likely that there is a typos:

if (item.TypeSpecificValue < 0)
    if (item.TypeSpecificValue < 10) // This is always true ... should be > -10?
        c = (char)('0' - (char)item.TypeSpecificValue) // The - operator is corrective for a negative value

**Comment by Gurbintroll** [comment]
Fixed.
