### ISSUE TITLE
Starting index when accessing the ItemTypes array often incorrect

### ISSUE THREAD

**Issue by marcjohnston** [Gurbintroll/Cthangband#17]
There are 9 instances where a FOR loop is being used to loop through the ItemTypes array (List).

The WizardCommandHandler.WizCreateItemType and SaveGame.ApplyFlavourVisuals correctly start at index 0.
The remaining instances skip the item at index 0.  
Journal.WorhlessItemTypeSelection (3 instances)
Player constructor
SaveGame.FlavorInit
SaveGame.InitializeAllocationTables (2 instances)
Store constructor
WizardCommandHandler.DoCmdWizLearn

It appears that the FOR loops could be converted to FOREACH loops to prevent this issue.

**Comment by Gurbintroll** [comment]
Fixed.
