### ISSUE TITLE
GetAbilitiesAsItemFlags Method Matches HighElf Twice

### ISSUE THREAD

**Issue by marcjohnston** [Gurbintroll/Cthangband#18]
There are two matches for HighElves and the DarkElf is missing.  Assuming DarkElves resist light ... making the first case a typo.
            if (RaceIndex == RaceId.HighElf)
            {
                itemCharacteristics.ResLight = true;
            }
            if (RaceIndex == RaceId.HighElf)
            {
                itemCharacteristics.SeeInvis = true;
            }

**Comment by Gurbintroll** [comment]
The code is technically correct, as high elves do get both of those abilities, and dark elves are matched and given their abilities further down in the file.

However, the two consecutive 'if' statements are redundant and I've combined them into one.

(The same thing is present in Player.CalcBonuses() so I've fixed that too.)
