### ISSUE TITLE
Two wrong constants used in ItemForge.

### ISSUE THREAD

**Issue by marcjohnston** [Gurbintroll/Cthangband#2]
File ItemForge.cs, line 4155 references Constants.SummonElemental.  Should be RandomArtifactPower.ActSummonElemental.

As is, if chosen, the constant value of 48 will not be processed by the ActivateRandomArtifact and will result in

                default:
                    Profile.Instance.MsgPrint($"Unknown activation effect: {item.BonusPowerSubType}.");
                    return;
Also,

File ItemForge.cs, line 4159 references Constants.SummonPhantom.  Should be RandomArtifactPower.ActSummonPhantom.

As is, if chosen, the constant value of 47 will not be processed by the ActivateRandomArtifact and will result in

                default:
                    Profile.Instance.MsgPrint($"Unknown activation effect: {item.BonusPowerSubType}.");
                    return;

**Comment by Gurbintroll** [comment]
Fixed
