### ISSUE TITLE
ProjectIce wrong stun immunity

### ISSUE THREAD

**Issue by marcjohnston** [Gurbintroll/Cthangband#23]
When the ProjectIce affects a monster, a stun value is computed.  The wrong immunity is being checked for the monster to avoid the stun ... the !rPtr.BreatheSound && !rPtr.BreateForce was copied from the ProjectForce ... it should be !BreatheCold.

**Comment by Gurbintroll** [comment]
This isn't actually using the wrong immunity.

Monsters that breathe sound or force are immune to stun regardless of what type of attack does the stunning just as monsters that breathe confusion or chaos resist confusion regardless of what type of attack does the confusing.

If you check the other projections that can either stun or confuse a monster (e.g. ProjectDomination, ProjectPsi, or ProjectGravity) you'll see that they all check the same immunities.
