### ISSUE TITLE
Priests can manually choose from Nature, Chaos, Tarot, Folk or Corporeal Realms but randomly picks Life or Death.

### ISSUE THREAD

**Issue by marcjohnston** [Gurbintroll/Cthangband#24]

**Comment by marcjohnston** [comment]
It appears that the realm1 choice system has been moved into the random choice and the realm2 choice system is the manual choice.

**Comment by bluetyson** [comment]
On a non-related note - do any of your rpgs have non-pdf versions anywhere?

**Comment by Gurbintroll** [comment]
Some of my RPGs are available in print at DriveThruRPG here:

https://www.drivethrurpg.com/browse/pub/9745/Gurbintroll-Games

Not all of them, though, because of art licensing issues.

**Comment by bluetyson** [comment]
Thanks - have most of those, but not Lightmaster, so will grab.

Non-pdf - as in text versions I was wondering.
