### ISSUE TITLE
Incorrect flags set in ItemForge in two locations ... line 331 and 360

### ISSUE THREAD

**Issue by marcjohnston** [Gurbintroll/Cthangband#7]
Setting the ItemFlag3.ShElec in line 331 and line 360 is setting the ItemFlag2 which would correspond to the SustInt.

                    if (_item.Category >= ItemCategory.Cloak &&
                        _item.Category <= ItemCategory.HardArmor &&
                        _item.RandartFlags3.IsClear(ItemFlag3.ShElec))
                    {
                        _item.RandartFlags2.Set(ItemFlag3.ShElec);    <---------------- Should be RandartFlags3
                        if (Program.Rng.DieRoll(2) == 1)
                        {
                            return;
                        }
                    }

**Comment by Gurbintroll** [comment]
Fixed
