### ISSUE TITLE
Unintended random resistance issue

### ISSUE THREAD

**Issue by marcjohnston** [Gurbintroll/Cthangband#9]
The specific parameter for recursive calls to forge.ApplyRandomResistance from specific switch cases is incorrect.

        public void ApplyRandomResistance(int specific)
        {
            ... omitted for brevity ...
            switch (specific != 0 ? specific : Program.Rng.DieRoll(41))
            {
                case 1:
                    if (Program.Rng.DieRoll(Constants.WeirdLuck) != 1)
                    {
                        ApplyRandomResistance(specific);  <-------- EXPECTED TO BE 0 OTHERWISE IT WILL LOOP UNTIL ROLL SUFFICES
                    }
                    else
                    {
                        _item.RandartFlags2.Set(ItemFlag2.ImAcid);
                        if (_artifactBias == 0)
                        {
                            _artifactBias = ArtifactBias.Acid;
                        }
                    }
                    break;

                case 2:

**Comment by marcjohnston** [comment]
This issue appears to be present in cases #1, 2, 3, 4, 39, 40 and 41.

**Comment by Gurbintroll** [comment]
Fixed.
